= Template for https://isaqb.org[iSAQB] Advanced Level Curricula

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-ddd/workflows/CI - Releases and Main/badge.svg?branch=main["CI"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-ddd/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-ddd.svg["Contributors",link="https://github.com/isaqb-org/curriculum-ddd/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-ddd.svg["Issues",link="https://github.com/isaqb-org/curriculum-ddd/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-ddd.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-ddd/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the curriculum for the https://www.isaqb.org/de/zertifizierungen/zertifizierungen-uebersicht/cpsa-advanced-level/ddd-domain-driven-design/#faqs[iSAQB Advanced Level *DDD*] in AsciiDoc. It is maintained by its curators.

toc::[]

== How to contribute or participate
We publish our curricula on Github to enable everyone to contribute and make suggestions how to evolve the software architecture education.
To do this you can create an issue or a pull-request to propose additions or changes.

If you are not familiar with Asciidoc, yet, the https://asciidoctor.org/docs/asciidoc-writers-guide/[Asciidoctor Writer's Guide] is good first place to visit.
This guide will also be a great companion during your work with this repository.

== How to work with this curriculum

. Either click on "Clone" in the GitHub UI or Clone the repository - including the submodule - via your git command line interface (CLI):
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-ddd.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-ddd.git --recursive
----
--
. If you don't have Java installed, https://openjdk.java.net/projects/jdk/[install a JDK]
. Build the project with http://www.gradle.com[gradle] via the shell command `./gradle-tools/gradlew buildDocs` (NOTE: the `java` executable must be on your PATH for gradle to work properly)
. Once the "BUILD SUCCESSFUL" is show, you can review the created files in the subdirectory `./build/index.html`


== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Carola Lilienthal, Benjamin Wolf, and Alexander Heusingfeld.
It was forked from https://github.com/isaqb-org/curriculum-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
