=== {learning-goals}


// tag::DE[]
Dieser Block vermittelt Ansätze, mit denen die Konsistenz innerhalb eines Modells sichergestellt werden kann und wann es dafür notwendig ist, Teile des Modells auszugliedern.

[[LZ-6-1]]
==== LZ 6-1: Team-Abhängigkeiten verstehen und bewerten
* Die TN können beurteilen, welche Team-Abhängigkeit zwischen zwei Teams / Bounded Contexts bestehen.
* Die TN kennen die drei von Domain-Driven Design propagierten Arten von Team-Abhängigkeiten und deren Einfluss auf das Design des Systems:
** Mutual Dependency
** Upstream-Downstream
** Free

[[LZ-6-2]]
==== LZ 6-2: Context Mapping Patterns verstehen, erkennen und gezielt einsetzen
* Die TN kennen mindestens fünf der folgenden Patterns, die in einer Context Map verwendet werden können:
** Open-Host Service
** Anticorruption Layer
** Separate Ways
** Shared Kernel
** Customer-Supplier
** Conformist
** Published Language
** Partnership
** Big Ball Of Mud 
* Die TN können die Vor- und Nachteile der oben genannten Patterns im System-Design bewerten, sowohl im Allgemeinen als auch situativ (beispielsweise unter Berücksichtigung strategischer Klassifizierungen).
* Die TN können Patterns im Kontext der in LZ 6-1 erwähnten Team-Abhängigkeiten bewerten und korrekt einsetzen.

[[LZ-6-3]]
==== LZ 6-3: Domain Events als Kommunikationsmittel zwischen Bounded Contexts nutzen können
* Die TN verstehen, dass Domain Events den Publisher vom Subscriber entkoppeln.
** Insbesondere verstehen die TN, dass dies für den Publisher bedeutet, dass es für ihn nicht relevant ist, wer seine Events verarbeitet.
* Die TN sind in der Lage Domain Events als Kommunikationsmittel zwischen Bounded Contexts zu entwerfen.
* Die TN sind in der Lage, Chancen und Risiken von Domain Events in diesem Zusammenhang abzuwägen:
** Wenn Events trotz vorhandener Abhängigkeiten (z. B. innerhalb eines Bounded Contexts) eingesetzt werden, besteht das Risiko, dass dadurch die Abhängigkeiten nur versteckt werden und zur Laufzeit zu schwer nachvollziehbaren Kontrollflüssen führen.

// end::DE[]

// tag::EN[]
This section teaches approaches with which the consistency within a model can be ensured as well as when it is necessary to separate parts of the model.

[[LG-6-1]]
==== LG 6-1: Understanding and evaluating team dependencies
* Participants can assess which team dependencies exist between two teams / bounded contexts.
* Participants are familiar with the three types of team dependencies publicized by Domain-Driven Design and their impact on system design:
** Mutual Dependency
** Upstream-Downstream
** Free


[[LG-6-2]]
==== LG 6-2: Understanding, identifying, and effectively applying context mapping patterns
* Participants should be familiar with at least five of the following patterns that can be used in a context map:
** Open-Host Service
** Anticorruption Layer
** Separate Ways
** Shared Kernel
** Customer-Supplier
** Conformist
** Published Language
** Partnership
** Big Ball Of Mud 
* Participants can evaluate the advantages and disadvantages of the above-mentioned patterns in system design, both in general and in specific contexts (for example, taking strategic classifications into account).
* Participants can evaluate patterns in the context of the team dependencies mentioned in LG 6-1 and apply them correctly.

[[LG-6-3]]
==== LG 6-3: Be able to use Domain Events as a means of communication between Bounded Contexts
* The course participants understand that Domain Events decouple the Publisher from the Subscriber.
** In particular, the course participants understand that, for the Publisher, this means that it is not relevant for him who processes his events.
* The course participants are able to create Domain Events as a means of communication between Bounded Contexts.
* The course participants are able to assess opportunities and risks of Domain Events in this context:
** If events are used despite existing dependencies (e.g., within a Bounded Context), there is a risk that the dependencies will only be hidden, which could lead to control flows that are difficult to understand at runtime.
* The course participants are able to use an event store (cf.: page 539 <<vernon>>) to allow Subscribers to reprocess events that were incorrectly processed.

// end::EN[]
