// tag::DE[]
=== Voraussetzungen

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

- Grundlagen und weiterführende Konzepte der objektorientierten Software-Entwicklung
- Erfahrungen bei der Modellierung von objektorientierten Architekturen

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:

- Wissen über agile Methoden der Software-Entwicklung, wie z. B. Scrum, Kanban, XP, etc.
- Erfahrung bei der Zusammenarbeit von Fachbereich und Software-Entwicklern.

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Fundamentals and advanced concepts of object-oriented software development
- Experience in modeling object-oriented architectures

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Knowledge of agile methods of software development, such as Scrum, Kanban, XP, etc.
- Experience in collaboration between business experts and software developers.
// end::EN[]
