=== {learning-goals}


// tag::DE[]
Dieser Block vermittelt die Grundlagen dafür, ein Modell in mehrere Teilmodelle aufzuspalten und durch definierte Modellgrenzen beherrschbar zu machen.
Zudem vermittelt er Strategien, um mehrere Modelle, und die daraus erwachsenden Verantwortungen auf verschieden Teams zu verteilen. Es werden Lösungen aufgezeigt, mit denen sich Schnittstellen zwischen Modellen gestalten lassen.

[[LZ-5-1]]
==== LZ 5-1: Symptome kennen, die bei zu großen Modellen auftreten können
* Die TN können die folgenden Sachverhalte als Symptom identifizieren:
** Verschiedene Anwendergruppen verwenden dieselben Begriffe auf unterschiedliche Art und Weise.
** Das Modell lässt sich nicht mehr von einem Entwickler-Team bewältigen. 
** Das Modell wirkt widersprüchlich.

[[LZ-5-2]]
==== LZ 5-2: Vor- und Nachteile eines Team-Übergreifenden Modells abwägen können
* Die TN kennen Conway's Law footnote:7[Cf.: <<conway>>] und können es auf die (Kommunikations-)Struktur von Entwicklungs-Teams und Software-Artefakten anwenden.
* Die TN verstehen, dass von mehreren Teams genutzte Modelle teamübergreifende Kommunikation und Koordination (z. B. beim Deployment) erfordern.
* Die TN verstehen, dass Modelle aufgeteilt werden müssen, damit mehrere Entwicklungsteams unabhängig voneinander arbeiten können.
* Die TN verstehen, dass definierte Modellgrenzen eine wichtige Rolle dabei spielen, den Kommunikationsaufwand gering zu halten.
* Die TN wissen, dass Begriffe der Fachsprache in verschiedenen Kontexten verschiedene Bedeutungen haben können.
* Die TN wissen, dass lokale Modellkonsistenz unabhängig von anderen Modellen aufrechterhalten werden kann.

[[LZ-5-3]]
==== LZ 5-3: Modellgrenzen von Bounded Contexts in einer Context Map beschreiben können
* Die TN können die Beziehungen zwischen mehreren Bounded Contexts als Context Map abbilden.
* Die TN verstehen, dass jedes Modell einen Kontext hat, auch wenn er nicht explizit ist.
* Die TN verstehen, dass die Begriffe der Ubiquitous Language nur innerhalb ihres Kontexts eine Bedeutung haben.
* Die TN verstehen, dass bei der Interaktion von verschiedenen Bounded Contexts die Bausteine der jeweiligen Kontexte ineinander übersetzt werden müssen.
* Die TN verstehen, die Vorteile der Korrelation zwischen den Modellgrenzen, der Organisationsstruktur und des Sourcecodes.

[[LZ-5-4]]
==== LZ 5-4: Kern-Elemente mehrerer Teilmodelle in einem Shared Kernel wiederverwenden können
* Die TN können die Angemessenheit eines Shared Kernels in einer konkreten Situation bewerten und ihn entwerfen.
* Die TN verstehen, dass ein Shared Kernel hilft, Modell-Übersetzungen zu vermeiden.
* Die TN verstehen, dass ein Shared Kernel ein großes Maß an Koordination der beteiligten Teams erfordert.
* Die TN verstehen, dass die Teams bei der Arbeit am Shared Kernel gleichberechtigt sind.

[[LZ-5-5]]
==== LZ 5-5: Schnittstellen bei Customer/Supplier Teams einsetzen können
* Die TN können beurteilen, ob zwei Teams sich in einer Customer/Supplier-Konstellation befinden.
* Die TN kennen die Rahmenbedingungen für die erfolgreiche Zusammenarbeit von Customer/Supplier Teams:
** Stabilität und Dokumentation der Schnittstelle sind wichtig für die Integration
** Gemeinsam entwickelte Akzeptanztests helfen, die Schnittstelle zu stabilisieren
** Voraussetzung für eine funktionierende Kunde/Anbieter-Beziehung ist ein Interesse des Anbieters an der Nutzung durch den Kunden
* Die TN wissen, dass in einer Kundenbeziehung der Kunde die Anforderungen an die Schnittstelle des Anbieters formuliert.

[[LZ-5-6]]
==== LZ 5-6: Ein System als Open Host Service (OHS) konzipieren können
* Die TN verstehen, dass ein OHS die fachlichen Übersetzungs-Schichten der Klienten ersetzt.
* Die TN können Services für einen OHS entwerfen. Sie sind in der Lage, essentielle Anforderungen von spezifischen zu unterscheiden und im Entwurf zu berücksichtigen.
* Die TN verstehen, dass eine öffentliche Schnittstelle punktuell für besondere Anforderungen einzelner Klienten erweitert werden kann, ohne die Schnittstelle der anderen Klienten zu beeinträchtigen.
* Die TN verstehen, dass sich ein OHS besonders lohnt, wenn mehrere Kunden eine Übersetzungs-Schicht benötigen.

[[LZ-5-7]]
==== LZ 5-7: Domain Events als Kommunikationsmittel zwischen Bounded Contexts nutzen können
* Die TN verstehen, dass Domain Events den Subscriber vom Publisher entkoppeln.
** Insbesondere verstehen die TN, dass dies für den Publisher bedeutet, dass es für ihn
* nicht relevant ist, wer seine Events verarbeitet.
* Die TN sind in der Lage Domain Events als Kommunikationsmittel zwischen Bounded Contexts zu entwerfen.
* Die TN sind in der Lage, Chancen und Risiken von Domain Events in diesem Zusammenhang abzuwägen:
** Wenn Events trotz vorhandener Abhängigkeiten (z. B. innerhalb eines Bounded Contexts) eingesetzt werden, besteht das Risiko, dass dadurch die Abhängigkeiten nur versteckt werden und zur Laufzeit zu schwer nachvollziehbaren Kontrollflüssen führen.
* Die TN sind in der Lage einen Event Store footnote:8[Vgl.: Seite 539 <<vernon>>] einzusetzen, um es den Subscribern zu ermöglichen, fehlerhaft verarbeitete Events erneut zu verarbeiten.


// end::DE[]

// tag::EN[]
This section teaches the fundamentals of decomposing a model into several sub-models and making the model manageable using defined model boundaries.
It also teaches strategies for distributing multiple models and their resulting responsibilities to various teams. Solutions are highlighted that allow interfaces to be created between models.

[[LG-5-1]]
==== LG 5-1: Know symptoms that can occur with excessively large models
* The course participants can identify the following circumstances as symptoms:
** Various user groups use the same terms in different ways. 
** The model can no longer be managed by a developer team. o The model appears inconsistent.

[[LG-5-2]]
==== LG 5-2: Be able to assess advantages and disadvantages of a cross-team model
* The course participants know Conway's Law footnote:7[Cf.: <<conway>>] and the impact that it can have on development teams and software artefacts.
* The course participants understand that models used by several teams require cross-team communication and coordination (e.g., for deployment).
* The course participants understand that models need to be partitioned so that several development teams can work independently of one another.
* The course participants understand that specified model boundaries play an important role in keeping the communication effort low.
* The course participants know that terms in the domain-specific terminology can have different meanings in different contexts.
* The course participants know that local model consistency can be maintained independently of other models.

[[LG-5-3]]
==== LG 5-3: Be able to describe model boundaries of Bounded Contexts in a Context Map
* The course participants can show the relationship between several Bounded Contexts as a Context Map.
* The course participants understand that every model has a context, even if it is not explicit.
* The course participants understand that the terms of the ubiquitous language only have meaning within their context.
* The course participants understand that, when different Bounded Contexts interact, the building blocks of one context need to be translated into the other context.
* The course participants understand the benefits of the correlation between the model boundaries, the organizational structure, and the source code.

[[LG-5-4]]
==== LG 5-4: Be able to reuse core elements of several partial models in a shared kernel
* The course participants can design and assess the suitability of a shared kernel for a specific situation.
* The course participants understand that a shared kernel helps to avoid model translations.
* The course participants understand that a shared kernel requires a high degree of coordination among the teams involved.
* The course participants understand that the teams are equally qualified to work on the shared kernel.

[[LG-5-5]]
==== LG 5-5: Be able to use interfaces for customer/supplier teams
* The course participants can assess whether two teams are located in one customer/supplier constellation.
* The course participants know the circumstances for the successful collaboration of customer/supplier teams:
** Stability and documentation of the interface are important for integration
** Jointly developed acceptance tests help to stabilize the interface
** The prerequisite for a functioning relationship is that the supplier has an interest in the customer actually using the interface
* The course participants know that, in a customer relationship, the customer formulates the requirements on the supplier's interface.

[[LG-5-6]]
==== LG 5-6: Be able to design a system as an open host service (OHS)
* The course participants understand that an OHS replaces the domain translation layers of the clients.
* The course participants can design services for an OHS. They are able to distinguish between essential and specific requirements and take this into account in the design.
* The course participants understand that a public interface can be extended selectively for specific requirements of individual clients, without impairing the interface of other clients.
* The course participants understand that an OHS is particularly worthwhile if several customers require a translation layer.

[[LG-5-7]]
==== LG 5-7: Be able to use Domain Events as a means of communication between Bounded Contexts
* The course participants understand that Domain Events uncouple the Subscriber from the Publisher.
o In particular, the course participants understand that, for the Publisher, this means that it is not relevant for him who processes his events.
* The course participants are able to create Domain Events as a means of communication between Bounded Contexts.
* The course participants are able to assess opportunities and risks of Domain Events in this context:
o If events are used despite existing dependencies (e.g., within a Bounded Context), there is a risk that the dependencies will only be hidden, which could lead to control flows that are difficult to understand at runtime.
* The course participants are able to use an event store footnote:8[Cf.: page 539 <<vernon>>] to allow Subscribers to reprocess events that were incorrectly processed.


// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
